{% set version = "3.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinyalert
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinyalert_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyalert/shinyalert_{{ version }}.tar.gz
  sha256: d4ea859610cda4adb7b48d8c7301112d598da9c442709b4ba9cf620bf5469abf

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools
    - r-knitr
    - r-shiny >=1.0.4
    - r-uuid
    - pandoc
  run:
    - r-base
    - r-htmltools
    - r-knitr
    - r-shiny >=1.0.4
    - r-uuid
    - pandoc

test:
  commands:
    - $R -e "library('shinyalert')"           # [not win]
    - "\"%R%\" -e \"library('shinyalert')\""  # [win]

about:
  home: https://cran.r-project.org/package=shinyalert
  dev_url: https://github.com/daattali/shinyalert
  doc_url: https://daattali.com/shiny/shinyalert-demo/
  license: MIT
  summary: Easily create pretty popup messages (modals) in 'Shiny'. A modal can contain text, images, OK/Cancel buttons, an input to get a response from the user, and many more customizable options.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shinyalert
# Title: Easily Create Pretty Popup Messages (Modals) in 'Shiny'
# Version: 1.0
# Authors@R: c( person("Dean", "Attali", email = "daattali@gmail.com", role = c("aut", "cre"), comment = "R interface"), person("Tristan", "Edwards", role = c("aut"), comment = "sweetalert library") )
# Description: Easily create pretty popup messages (modals) in 'Shiny'. A modal can contain text, images, OK/Cancel buttons, an input to get a response from the user, and many more customizable options.
# URL: https://github.com/daattali/shinyalert https://daattali.com/shiny/shinyalert-demo/
# BugReports: https://github.com/daattali/shinyalert/issues
# Depends: R (>= 3.0.2)
# Imports: digest, shiny (>= 1.0.4), stats
# Suggests: colourpicker, knitr, rmarkdown
# License: MIT + file LICENSE
# SystemRequirements: pandoc with https support
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-02-12 16:41:07 UTC; Dean
# Author: Dean Attali [aut, cre] (R interface), Tristan Edwards [aut] (sweetalert library)
# Maintainer: Dean Attali <daattali@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-02-12 18:20:44 UTC
